name: Build and Compile TypeScript

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Specify the Node.js version you want

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Compile TypeScript
      - name: Compile TypeScript
        run: cd ./packages/notion-astro-loader && npm run build

      # Step 5: Commit and Push compiled `dist/` folder
      - name: Commit and push `dist/` folder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f packages/notion-astro-loader/dist/ 
          git commit -m "Build: Add compiled files to dist folder"
          git push origin main
        continue-on-error: true


